bill:
  data:
    page-size: 8

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: localhost
    port: 1025
    username: user
    password: 12345
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            access-token-uri: ${google-access-token-uri}
            user-authorization-uri: ${google-user-authorization-uri}
            user-info-uri: ${google-user-info-uri}
            scope:
              - email
              - profile
              - openid

          facebook:
            client-id: ${facebook-client-id}
            client-secret: ${facebook-client-secret}
            scope:
              - email

          github:
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
            access-token-uri: ${github-access-token-uri}
            user-authorization-uri: ${github-user-authorization-url}
            user-info-uri: ${github-user-info-uri}
            scope:
              - email


